### ISSUE TITLE
Слетели значки прохождения уроков и подсветка синтаксиса в примерах

### ISSUE THREAD

**Issue by burenkov-anton** [hexlet-basics/hexlet-basics#112]
![Значки](https://user-images.githubusercontent.com/11513918/104603393-f171d700-56ae-11eb-853d-e0f8dba7450f.png)

![Нет подсветки](https://user-images.githubusercontent.com/11513918/104604127-b6bc6e80-56af-11eb-9559-ed2c33dcdc0b.png)

**Comment by amshkv** [comment]
Починили, спасибо!)
