### ISSUE TITLE
Неверная длинна таба в выводе решения студента

### ISSUE THREAD

**Issue by amshkv** [hexlet-basics/hexlet-basics#122]
Если самому поставить ТАБ с новой строки в редакторе он будет занимать 4 пробела
А в выводе решений - 8

![image](https://user-images.githubusercontent.com/23584933/105020939-05278f80-5a59-11eb-9518-b01060a7aac4.png)
![image](https://user-images.githubusercontent.com/23584933/105020961-0a84da00-5a59-11eb-89d1-d6e9a21039d4.png)

Если же нажимать enter, вставлять уже отформатированный код или добавлять табы пробелами - все выровнено как надо

UPD: такое поведение во всех языках. Таб будто бы в Решении учителя всегда в размер 8 пробелов

**Comment by GPopov9** [comment]
I'll take it
