### ISSUE TITLE
Нет понятного текста ошибки, когда регистрируешься с емейлом, который уже используется

### ISSUE THREAD

**Issue by kirill-chertkov** [hexlet-basics/hexlet-basics#125]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/29174482/105156171-872cbc80-5b1c-11eb-87c8-ac25c69435bf.png">
Если емейл уже используется в каком-то аккаунте, и пользователь пытается зарегестрироваться с ним, появляется вот такое сообщение. Нужен понятный текст. Возможно, сразу со ссылкой на страницу входа

**Comment by grozwalker** [comment]
Уже пофикшена
