### ISSUE TITLE
Добавить изображение на вкладку "Решение"

### ISSUE THREAD

**Issue by Melodyn** [hexlet-basics/hexlet-basics#143]
На вкладке "Решение" сейчас просто текст в окне:

![now](https://user-images.githubusercontent.com/26752238/111745065-2f50ce80-889d-11eb-89db-10c52f004d05.png)

Надо добавить туда изображение:
![2](https://user-images.githubusercontent.com/26752238/111745975-6b386380-889e-11eb-87a3-fef07a4e105f.png)

Чтобы было не так серо.

**Comment by fey** [comment]
https://github.com/hexlet-basics/hexlet-basics/pull/145 можно закрывать

**Comment by Melodyn** [comment]
Супер!
