### ISSUE TITLE
Добавить "автатар" пользователя

### ISSUE THREAD

**Issue by Melodyn** [hexlet-basics/hexlet-basics#144]
В дропдаун для пользователя добавить аватар:
![5-01-01](https://user-images.githubusercontent.com/26752238/111747611-8f953f80-88a0-11eb-95f5-7ec2eaca4fbd.png)

Как это сделано на Хекслете:
![image](https://user-images.githubusercontent.com/26752238/111747708-b5224900-88a0-11eb-90dd-2887a473b30a.png)

**Comment by Surtt** [comment]
Взял задачу

**Comment by ArtemRakov** [comment]
@Melodyn я бы взялся, но даже если добавить. То у нас нет никого форума или похожих вещей на бейсиксе, где фотка будет отображаться. Или это все в планах на добавление, а пока начнем с фотки?

**Comment by Melodyn** [comment]
Пока просто изображение сделать всем одинаковое. Будут ли фотки - не знаю.

**Comment by nunsez** [comment]
Пул реквест https://github.com/hexlet-basics/hexlet-basics/pull/159
