### ISSUE TITLE
Добавить ссылку на правила сообщества

### ISSUE THREAD

**Issue by fey** [hexlet-basics/hexlet-basics#151]
![image](https://user-images.githubusercontent.com/697178/117930742-cf642a80-b317-11eb-9c28-9dedc2612648.png)

Добавить ссылку на правила сообщества Hexlet
https://github.com/Hexlet/hexlet-slack-archive/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B0-%23general

**Comment by mokevnin** [comment]
А бог с ним
