### ISSUE TITLE
Добавить инструкцию/подсказку как пользоваться редактором/что возможно делать

### ISSUE THREAD

**Issue by fey** [hexlet-basics/hexlet-basics#152]
![image](https://user-images.githubusercontent.com/697178/117930906-fcb0d880-b317-11eb-847b-6571fd2f755a.png)

**Comment by Surtt** [comment]
Попробую сделать. Только мне нужны будут тексты?!

**Comment by mokevnin** [comment]
Добавил базовую подсказку. Теперь ее легко расширить через локаль.
