### ISSUE TITLE
Добавить форму для изменения пароля в профиле

### ISSUE THREAD

**Issue by chrtkv** [hexlet-basics/hexlet-basics#156]
Сейчас пароль можно только создать новый, если забыл. Но бывает, что пользователь пароль помнит, но хочет его изменить. Удобно было бы иметь для этого форму в профиле или отправлять ссылку, как на Хекслете.

**Comment by fey** [comment]
@mokevnin делаем эту штуку?

**Comment by usernaimandrey** [comment]
И хотелось бы узнать по ссылке или через форму?)

**Comment by mokevnin** [comment]
Оно того не стоит. Можно разлогиниться и запросить восстановление

**Comment by usernaimandrey** [comment]
> Оно того не стоит. Можно разлогиниться и запросить восстановление

Понял, принял
