### ISSUE TITLE
Предлагать перейти на русскую версию курса, если уроков нет или мало в английской версии

### ISSUE THREAD

**Issue by kirill-chertkov** [hexlet-basics/hexlet-basics#157]
Студент попадает на английскую версию Code Basics, открывает интересный ему курс и видит, что там нет уроков. Например, питон https://code-basics.com/languages/python:
![image](https://user-images.githubusercontent.com/29174482/119909397-64dcfc80-bf5d-11eb-9ea7-5be9ce8a2c24.png)

Если нажать на старт лернинг, студент получит 404, подумает, что тут ничего нет и уйдет

Предлагаю добавить информацию, что английских версий уроков пока нет и дать ссылку на уроки на русском языке.

**Comment by grozwalker** [comment]
@PlugIN73 вот смотри еще есть таск, который может помочь удерживать пользователей. Может сделаем?
