### ISSUE TITLE
Вывести описание языка/курса из репозитория языка

### ISSUE THREAD

**Issue by amshkv** [hexlet-basics/hexlet-basics#161]
Сейчас описание языка берется из переводов. 
![image](https://user-images.githubusercontent.com/23584933/120199410-e10c6400-c22b-11eb-828b-4f8b08696dfe.png)

Это логичнее хранить в репозитории языка в spec.yml файле
Нужно написать загрузку и сохранение этого поля к нам

(в спек ямл пока пусто, можно добавить текущие переводы)

**Comment by mokevnin** [comment]
fixed
