### ISSUE TITLE
Сделать функцию выбора студентом закрывать ли автоматически теги

### ISSUE THREAD

**Issue by Ananasovna** [hexlet-basics/hexlet-basics#179]
Всем привет!
Прохожу курс HTML, и в нем теги закрываются автоматически, отменить это нельзя. Предлагаю добавить функцию, чтобы студент мог выбрать, включать ли автоматическое закрытие тегов или нет. Т.к. я учусь с нуля прежде чем прибегать к таким способам упрощения работы, я хочу натренировать привычку закрывать теги самостоятельно.

**Comment by vladimironokhov** [comment]
Поддерживаю.

**Comment by mokevnin** [comment]
Ребят, тут мы врядли можем помочь, сам редактор это внешняя библиотека, мы ей не управляем практически.

**Comment by frontstall** [comment]
сменили редактор, теги сами не закрываются (но помогает закрыть тег правильно с помощью подказки)
