### ISSUE TITLE
Сделать однозначный индикатор-переключатель языка

### ISSUE THREAD

**Issue by kirill-chertkov** [hexlet-basics/hexlet-basics#181]
Сейчас флажок — это не индикатор текущего языка, а кнопка "Хочу такой язык". То есть, когда включен русский язык, отображается британский флаг и нажатие на него включает английский язык.

Это запутывает студентов

Возможное решение — сделать понятный индикатор текущего языка. Например, показывать рядом оба флага, и неактивный язык сделать черно-белым, а активный — цветным. 
![Untitled](https://user-images.githubusercontent.com/29174482/125129809-ad650980-e108-11eb-95ad-1cb10f607c5e.jpg)

**Comment by kirill-chertkov** [comment]
Или просто текстом — Ru/En

**Comment by mokevnin** [comment]
fixed, soon be released
