### ISSUE TITLE
После смены языка редиректить на тот же урок, на котором находился пользователь

### ISSUE THREAD

**Issue by chrtkv** [hexlet-basics/hexlet-basics#187]
Сейчас происходит редирект на главную. Если такой же урок есть на другом языке, удобнее будет остаться на той же странице. Если урок не переведен, показывать сообщение, что этот урок есть только на русском и сразу предлагать вернуться на русскую версию

**Comment by mokevnin** [comment]
Пока у нас на английском считай контента никакого, поэтому смысла мало, кроме того, делать разные редиректы в зависимости от ситуации (иногда на главную, иногда на урок) не правильно с точки зрения ux
