### ISSUE TITLE
редирект на языковую версию для поисковых систем

### ISSUE THREAD

**Issue by prio65** [hexlet-basics/hexlet-basics#188]
нужно убрать редирект для поисковых систем
сейчас с основного домена происходит на поддмен ру, нужно убрать редирект для поисковых систем (как вариант по Юзер-агенту)
если будет редирект по IP на основе страны которой принадлежит адрес, то в случае если на сайт попадает робот поисковых систем, редирект тоже не должен происходить

**Comment by mokevnin** [comment]
fixed
