### ISSUE TITLE
поправить стили для отображения контента на AMP страницах уроков 

### ISSUE THREAD

**Issue by prio65** [hexlet-basics/hexlet-basics#197]
нужно поправить стили в АМП версиях уроков, сейчас вот так https://drive.google.com/file/d/1XrBH2rpA68Sje6KBETQLS7_aMOTSsAKr/view?usp=sharing

пример страницы https://ru.code-basics.com/languages/css/lessons/introduction.amp

нужно: 
сделать отступы
ограничить ширину контента
сделать форматирование заголовков и контента (текст, ссылки, списки и тд)

ссылка на спецификацию https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/?referrer=ampproject.org#links

за основу можно взять внешний вид амп на гайдах (пример https://guides.hexlet.io/amp/encoding)

**Comment by mokevnin** [comment]
@amshkv давай действительно оттуда стили скопируем
