### ISSUE TITLE
доработать ссылку на полную версию страницы  

### ISSUE THREAD

**Issue by prio65** [hexlet-basics/hexlet-basics#198]
на AMP страницах уроков, в верхней части страницы выводится ссылка на полную версию 

вот здесь 
![image](https://user-images.githubusercontent.com/85234845/127786070-2d8f2219-10f5-4232-91c1-2afa9eab06c2.png)

**нужно сделать следующее** 
1 - перенести ссылку вниз. 
Она должна выводиться после задания. Вот здесь: 
![image](https://user-images.githubusercontent.com/85234845/127786089-12cd783b-dee2-434a-96fc-c4462885b5ba.png)

2 -  сделать её в виду кнопки 

вот так 
![image](https://user-images.githubusercontent.com/85234845/127786141-6a9c1d4e-2e37-4e64-8765-6656c7ba644d.png)

пример здесь https://guides.hexlet.io/amp/deploy

3 - заменить текст на кнопке на "Реактор кода доступен в основной версии"

**Comment by mokevnin** [comment]
@amshkv глянь плс, если все сделано, то закрываем
