### ISSUE TITLE
Отображение 500 etc

### ISSUE THREAD

**Issue by amshkv** [hexlet-basics/hexlet-basics#207]
Нужны добровольцы чтобы поправить отображение 500 страниц с дефолтных рельсовых на что-то поинтереснее.
Картинки 500 с хекслета уже лежат в ассетах

**Comment by Northrain-cmd** [comment]
Я этим займусь

**Comment by Northrain-cmd** [comment]
Но разве это уже не работает? 
https://ru.code-basics.com/tt
![Uploading Screenshot_2021-08-25-09-22-17-409_com.android.chrome.png…]()

**Comment by amshkv** [comment]
404 уже есть, вы правы, мой косяк

**Comment by Northrain-cmd** [comment]
Там уже все есть вроде, вьюшки лежат, контроллер errors  тоже

**Comment by amshkv** [comment]
тогда извиняюсь за беспокойство и закрываю тикет
