### ISSUE TITLE
логирование прогресса по обучения

### ISSUE THREAD

**Issue by prio65** [hexlet-basics/hexlet-basics#209]
**проблема следующая** 
мы сейчас во всех CTA баннерах пишем про отслеживание и сохранение прогресса, но этого нет на кодбейсике 
![image](https://user-images.githubusercontent.com/85234845/130945710-4333b712-904b-4bb2-a5cd-bb06170d08da.png)

**решение**
идея в том, чтобы реализовать логировние обучения для авторизованных пользователей 

в самом простом варианте это может выглядеть так: 
после нажатия кнопки "проверить", при успешном прохождении тестов - сохранять содержимое вкладки "решение" 
![image](https://user-images.githubusercontent.com/85234845/130947382-1c6182bc-81d1-4c0b-bb67-25bb4a7db97f.png)

нам по сути нужно: id пользователя, id курса, id урока, время действия, решение. 

в сложном варианте нужно зафиксировать следующее: 
факт начала урока 
отправка решения по кнопке проверить (со статусом - успешно или нет) - каждая отправка на проверку с содержимым вкладок вывод и решение 
просмотр решения урока - если не дали решение и просмотрели готовое решение учителя 

в идеале нужно и в интерфейсе курсов сделать метки и ярлыки для курсов и уроков
метки курсов: 
неначатый курс - без меток 
начатый но незавершенный курс - метка или процент завершенных уроков 
завершенный курс - метка или ярлык 

метки уроков аналогично, но без процента для незавершенных 

сделать личный кабинет с прогрессом 
![image](https://user-images.githubusercontent.com/85234845/130948996-7946589b-6d57-493f-bff3-0edb107942e3.png)

в разделе сделать список всех курсов в которых есть пройденные уроки 
для каждого курса вывести список уроков в которых есть активность и статус (не завершен/завершен) со ссылками на сам урок и просмотр решения (в максимальном варианте вывести все отправки на проверку и статус со ссылкой на просмотр)  

все сортировки действий внутри уроков по времени действия
сортировки уроков внутри курса - по id урока (по порядковому номеру в курсе)

**Comment by usernaimandrey** [comment]
Привет! Актуална ли данная задача?

**Comment by amshkv** [comment]
@usernaimandrey ушел уточнять, актуальна ли она, кажется что ее надо будет распиливать на более мелкие

**Comment by usernaimandrey** [comment]
@amshkv хорошо, ну да задача большая надо декомпозировать

**Comment by amshkv** [comment]
уточнил что эта задача не актуальна

**Comment by usernaimandrey** [comment]
Окей
