### ISSUE TITLE
Нажатие на кнопки Continue Learning и Start Learning внутри курсов дают 404

### ISSUE THREAD

**Issue by kirill-chertkov** [hexlet-basics/hexlet-basics#214]
Кнопки Continue Learning и Start Learning внутри курса на бейсиксе "рассчитывают" на то, что в английской версии есть те же уроки, что и в русской. В итоге, когда таких уроков нет, — получаем 404.

https://user-images.githubusercontent.com/29174482/134094706-48a0cb28-1cb4-4d28-853a-05089c4242da.mov

**Comment by ralder** [comment]
now error is gone
