### ISSUE TITLE
Работает переход на следующее задание при активации перехода на "Следующее" через таб-навигацию

### ISSUE THREAD

**Issue by fey** [hexlet-basics/hexlet-basics#276]
При не завершённом задании можно перейти на следующее задание, если сделать кнопку активной через Tab-навигацию
![image](https://user-images.githubusercontent.com/697178/148728967-6eee83cd-5b81-4ab9-bd68-cade3dbab3f8.png)

Т.е. событие будет не через клик, а через переход (нажатие enter).

При этом ссылка такого вида https://ru.code-basics.com/languages/java/lessons/statements/next_lesson
и может появиться ошибка 404

Почему это баг: фича таб-навигации сделана через браузеры и некоторые студенты ей пользуются

**Comment by letzabelin** [comment]
Можно закрывать, если задеплоили уже
