### ISSUE TITLE
Ряд незавершенных курсов отмечены как завершенные

### ISSUE THREAD

**Issue by burenkov-anton** [hexlet-basics/hexlet-basics#277]
Курс отмечен завершенным
![Go-Congrat](https://user-images.githubusercontent.com/11513918/148770346-c454a133-cc84-4a8d-a215-432cf8e8c996.png)

Но есть непройденные уроки
![Go-real](https://user-images.githubusercontent.com/11513918/148770361-32b4b8b7-9283-40ea-b196-173e422e1508.png)

**Comment by fey** [comment]
Привет, а ты проходил уроки? Возможно на момент не было новых уроков и курс засчитался завершенным

**Comment by burenkov-anton** [comment]
Привет, точно не вспомню - возможно. Подобная ситуация была с Java - там точно все проходил, завершил, уроки появились, курс остался завершенным (сейчас все пройдены).
