### ISSUE TITLE
Добавить вывод номеров строк во вкладку с тестами

### ISSUE THREAD

**Issue by mokevnin** [hexlet-basics/hexlet-basics#291]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/308430/156041342-21bd272c-e2b2-44a7-8788-e2f67b77f7ae.png">

**Comment by fey** [comment]
https://github.com/hexlet-basics/hexlet-basics/commit/bc0cce1c331673047eebe74bd89451242379a471
