### ISSUE TITLE
Выпадающее меню "Выберите курс" не помещается в 1080p высоту

### ISSUE THREAD

**Issue by ashikov** [hexlet-basics/hexlet-basics#316]
Можно сделать мега-меню в несколько столбцов, например: https://bootstrap-menu.com/demos/megamenu.html
Тут много разных вариантов: https://bootstrap-menu.com/

**Comment by warpedrhubarb** [comment]
@ashikov Поресерчил варианты как это можно реализовать без дополнительных пакетов вроде yamm и с минимальным количеством кастомного кода. Релизовал [вот такой вариант мегаменю (секция 'css' в начале файла).](https://github.com/warpedrhubarb/hexlet-basics/blob/8b0ef9dd8290d45cca628e931ef45b23e7f2f487/app/views/layouts/shared/_nav.html.slim)
Но не уверен что добавлять кастомный CSS прямо в slim файл это хорошая идея.
Буду признателен если подскажете как вместо этого переместить эти стили в app/assets/stylesheets/custom.scss
У меня стили из scss файла почему-то не подгружались 🤷

**Comment by ashikov** [comment]
@Psixodelik глянь, плиз

**Comment by amshkv** [comment]
Там сейчас в списке языки и завершенные, и в разработке
Думаю можно по этому принципу разделить на 2 колонки
а сами колонки уже сделать или через флекс, или через сгенерированную утилиту/компонент

**Comment by warpedrhubarb** [comment]
@amshkv а где хранится информация о том завершен язык или в разработке^ в параметре `info.language_version.state`? Или `info.language.progress`?

В запущенном мной инстансе подгружаются только 3 языка - javascript, ruby и php. И у всех трех параметр `info.language_version.state` равен `created`, а `info.language.progress` равен `completed`.

**Comment by amshkv** [comment]
info.language.progress

**Comment by amshkv** [comment]
https://github.com/hexlet-basics/exercises-typescript/blob/main/spec.yml#L9

**Comment by amshkv** [comment]
https://github.com/hexlet-basics/hexlet-basics/blob/main/make-compose-app.mk#L27-L51 - ты всегда можешь подгрузить другие языки (да и при старте ставится много чего)

**Comment by warpedrhubarb** [comment]
@amshkv 
Разделил на колонки по параметру `info.language.progress` с помощью флекса: [https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L17-L32](url)

вот так это выглядит:
[https://user-images.githubusercontent.com/7108262/194617475-ba746804-ffc6-4163-a83a-e7300f1bd154.png
](url)

Что скажете? Может есть какие то идеи или предложения как можно улучшить?

**Comment by amshkv** [comment]
> Может есть какие то идеи или предложения как можно улучшить?
Возможно стоит добавить пояснения, справа можно написать что в разработке, а что слева, пока никак не придумал
еще кажется что правый блок можно тоже разделить на 2, но это опционально

а вы запускали линетр? слим линт проходит без проблем? у меня ругается на ваш код :)

ПыСы: такие штуки лучше обсуждать в ПРе, чтобы было удобнее ссылаться

https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L18-L19 - `div` писать не обязательно, `.class` уже превратится в `<div class="class"></div>`

https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L21 и https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L28
вообще не ruby way сравнения, еще и сравнения со строками, что нехорошо
тогда лучше сравнивать вот так `info.language.progress.completed?`

https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L19 зачем тут `div.flex-column`, если он никак не отрабатывает?

https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L17-L19
<img width="991" alt="image" src="https://user-images.githubusercontent.com/23584933/194849257-adde8ff4-bc98-405d-85c0-1ab47fb5ae27.png">
невалидная верстка, див не может находиться в ul

https://github.com/warpedrhubarb/hexlet-basics/blob/07cfabcc47800362bef8d374c1be045fa2471163/app/views/layouts/shared/_nav.html.slim#L19-L33 если правильно сгруппировать выборку или вынести код самих кнопок в отдельный partial, то можно избежать дублирования
