### ISSUE TITLE
Отсутствует export default в уроке 9 по typescript

### ISSUE THREAD

**Issue by Takaiva** [hexlet-basics/hexlet-basics#318]
До 9 урока во всех предыдущих упражнениях заранее давалось конкретное имя функции, которую надо реализовать, а в редакторе заранее был прописан "export default *functionName*".

В 9 уроке дефолтный экспорт не записан, что по крайней мере нелогично на фоне предыдущих уроков + в таком случае в самом задании не прописано "Реализуйте ~~и экспортируйте по умолчанию~~ функцию getParams...".

В последующих уроках дефолтный экспорт так же заранее прописан.

**Comment by sgmdlt** [comment]
Добрый день, поправили.

ПС. Ишьюсы по тайпскрипту присылайте в https://github.com/hexlet-basics/exercises-typescript
