### ISSUE TITLE
Исправить отображение картинок в превью

### ISSUE THREAD

**Issue by acidmaksim** [hexlet-basics/hexlet-basics#329]
Сделать так, чтобы в превью отображались картинки с курса. Сейчас это не просто картинка, это svg без фона, а фон задается через css. т.е. это не png, jpg, поэтому выглядит так плохо
![image](https://user-images.githubusercontent.com/77053797/206190953-56e5e554-7ce8-42a6-b399-0aa14b87af75.png)

**Comment by alexkwyk** [comment]
возьму в работу

**Comment by alexkwyk** [comment]
Как я понимаю изображения подтягиваются через мета теги [Open Graph](https://ruogp.me/), который не дает возможности задать фон и все картинки языков заточены на использование фона, как вариант можно использовать логотип с главной страницы для всех языков либо добавить раскрашенные версии картинок в assets

**Comment by acidmaksim** [comment]
@fey посмотри, пожалуйста

**Comment by fey** [comment]
Давайте с логотипом попробуем.

**Comment by fey** [comment]
Привет, пообщался с Кириллом. Решили убрать прозрачность у картинок и задавать нужные цвета.
Нужно обновить картинки и вместо прозрачности подставить нужный цвет.

**Comment by alexkwyk** [comment]
#348
