### ISSUE TITLE
access denied при клонировании репо

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/hexlet-basics#402]
пробую склонировать hexlet-basics в /opt/projects, как требует того ридми. Получаю access denied

что мне поправить, чтобы успешно склонироваться?

![Screenshot from 2023-08-26 13-44-24](https://github.com/hexlet-basics/exercises-typescript/assets/93836126/b902501e-8733-489d-a4df-9a251317aabc)

![Screenshot from 2023-08-26 13-45-01](https://github.com/hexlet-basics/exercises-typescript/assets/93836126/b14ef99f-01f8-480c-8020-f5490b74b044)

**Comment by usernaimandrey** [comment]
В ридми написанно если возможно то с клонируйте в /opt/projects  но это не обязательное условие, попробуйте с клонировать в свою home дирректорию и сделать make project setup

**Comment by evgeniyworkbel** [comment]
> В ридми написанно если возможно то с клонируйте в /opt/projects но это не обязательное условие, попробуйте с клонировать в свою home дирректорию и сделать make project setup

окей, сделаю так. Есть предположения, почему не дает склонировать в /opt ? я думал возможно с правами доступа, но я предоставил все права и ошибка осталась

**Comment by usernaimandrey** [comment]
А еще надо же делать форк репозитория и клонировать свой форк и собственно вся работа и комиты вы будете присылать через форк, а так клон через ssh оригинальной репы не выдет

**Comment by evgeniyworkbel** [comment]
> А еще надо же делать форк репозитория и клонировать свой форк и собственно вся работа и комиты вы будете присылать через форк, а так клон через ssh оригинальной репы не выдет

я пробовал форк склонять - та же ошибка

**Comment by fey** [comment]
Проверьте есть ли директория и какие на нее права. Необходимы права на чтение и запись.

**Comment by fey** [comment]
```
 $ ls -la | grep projects
drwxr-xr-x  3 feycot feycot  4096 дек 30  2022 projects
```
мой пример.

**Comment by evgeniyworkbel** [comment]
> Проверьте есть ли директория и какие на нее права. Необходимы права на чтение и запись.

права все еще вчера предоставил и была ошибка такая же.
Но сейчас попробовал сначала по https склонить - поставилось. После этого попытался по ssh - и тоже получилось. не знаю, что за магия) ишьюс закрываю
