### ISSUE TITLE
Добавить креды для админки в README

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/hexlet-basics#404]

**Comment by evgeniyworkbel** [comment]
взял в работу

**Comment by evgeniyworkbel** [comment]
> а какие креды Вы хотите добавить, что то не получается?
> 
> если вы хотите зайти под админом в дев окружении то при разварачивании проекта локально у вас загружаются тестовые пользователи, ползовател: [full@test.io](mailto:full@test.io) пароль password - это админ

да, но об этом логине/пароле не узнаешь, пока не спросишь контрибьюторов. Эти креды можно добавить в сам ридми. Вот кстати переписка в тг хекслета https://t.me/hexletcommunity/12/61917

**Comment by fey** [comment]
https://github.com/hexlet-basics/hexlet-basics/pull/406
