### ISSUE TITLE
Как сделать коммит в свой форк этого репо?

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/hexlet-basics#405]
Не могу сделать коммит - вылетает ошибка

![image](https://github.com/hexlet-basics/hexlet-basics/assets/93836126/7ea17318-2b72-4891-b365-4bcfa8562ab6)

**Comment by usernaimandrey** [comment]
попробуйте переинициализировать репозиторий
https://www.airplane.dev/blog/fixing-fatal-not-a-git-repository-error

**Comment by usernaimandrey** [comment]
можно еще добавлять флаг --no-verify : git commit -m 'lalajopa' --no-verify
но тогда пред комитом надо вручную запускать тесты и линтер, потому что с этим флагом не будет git хук запускатся

еще вот тут может ответ есть https://github.com/typicode/husky/issues/500

**Comment by evgeniyworkbel** [comment]
> попробуйте переинициализировать репозиторий https://www.airplane.dev/blog/fixing-fatal-not-a-git-repository-error

сделал все шаги - не помогло

**Comment by evgeniyworkbel** [comment]
> можно еще добавлять флаг --no-verify : git commit -m 'lalajopa' --no-verify но тогда пред комитом надо вручную запускать тесты и линтер, потому что с этим флагом не будет git хук запускатся
> 
> еще вот тут может ответ есть [typicode/husky#500](https://github.com/typicode/husky/issues/500)

а вот это помогло, спасибо. Даже не потребовалось запускать тесты и линтер

**Comment by usernaimandrey** [comment]
> > можно еще добавлять флаг --no-verify : git commit -m 'lalajopa' --no-verify но тогда пред комитом надо вручную запускать тесты и линтер, потому что с этим флагом не будет git хук запускатся
> > еще вот тут может ответ есть [typicode/husky#500](https://github.com/typicode/husky/issues/500)
> 
> а вот это помогло, спасибо. Даже не потребовалось запускать тесты и линтер

Запуск тестов и линтера нужен для себя, так как вы поставили флаг --no-verify и из-за этого они не запустились автоматически при при коммите(по хуку)

**Comment by evgeniyworkbel** [comment]
> > > можно еще добавлять флаг --no-verify : git commit -m 'lalajopa' --no-verify но тогда пред комитом надо вручную запускать тесты и линтер, потому что с этим флагом не будет git хук запускатся
> > > еще вот тут может ответ есть [typicode/husky#500](https://github.com/typicode/husky/issues/500)
> > 
> > 
> > а вот это помогло, спасибо. Даже не потребовалось запускать тесты и линтер
> 
> Запуск тестов и линтера нужен для себя, так как вы поставили флаг --no-verify и из-за этого они не запустились автоматически при при коммите(по хуку)

фронтенд можно проверять командой make app-check?

**Comment by usernaimandrey** [comment]
make lint-eslint - это имено eslint запустит,  make app-lint -  запустит все линтеры

**Comment by evgeniyworkbel** [comment]
> make lint-eslint - это имено eslint запустит, make app-lint - запустит все линтеры

а ты же говорил, что и тесты надо запускать перд noverify

**Comment by evgeniyworkbel** [comment]
часть решения проблемы есть в PR #415
