### ISSUE TITLE
bug: Не работает архивация отзыва

### ISSUE THREAD

**Issue by fey** [hexlet-basics/hexlet-basics#409]
Создать отзыв, опубликовать его. Отредактировать, отправить в архив

Упс, что-то пошло не так, наши программисты уже решают эту проблему

![image](https://github.com/hexlet-basics/hexlet-basics/assets/697178/481ca486-efd9-49d6-a8db-cac52cdaac6d)

**Comment by usernaimandrey** [comment]
https://github.com/hexlet-basics/hexlet-basics/commit/b4894807ed0a11608c805585616fb22e76979a22
