### ISSUE TITLE
Bug: нет возможности убрать опубликованную статью в "блоге"

### ISSUE THREAD

**Issue by fey** [hexlet-basics/hexlet-basics#410]
нет возможности выбрать другое состояние, отличное от публикации.
![image](https://github.com/hexlet-basics/hexlet-basics/assets/697178/5cae59f5-9421-4e36-a1dd-fe422566021a)

**Comment by usernaimandrey** [comment]
https://github.com/hexlet-basics/hexlet-basics/commit/b238288b1cd6a8112609fdbede28657692f22408
