### ISSUE TITLE
Указать в ридми про локальный пулл образа

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-basics/hexlet-basics#412]
Подробности: https://t.me/hexletcommunity/12/61915

**Comment by evgeniyworkbel** [comment]
взял в работу

**Comment by johanla0** [comment]
И ссылку заменить можно на телеграм, слак уже неактуален

**Comment by evgeniyworkbel** [comment]
> И ссылку заменить можно на телеграм, слак уже неактуален

в каком месте? в ридми нет ссылка на слак

**Comment by johanla0** [comment]
Ага, точно, из описания проекта на старую ветку ссылка была :)
