### ISSUE TITLE
Сделать скрипт для переезда на новую структуру курсов

### ISSUE THREAD

**Issue by fey** [hexlet-basics/hexlet-basics#422]
Кирилл в курсе по JS внес изменения по новой структуре. Коммит
https://github.com/hexlet-basics/exercises-javascript/commit/0c00892f85414d0e8473a85a51b265446ad1eb9f

Необходимо написать скрипт (язык не так важен, предпочтительны скриптовые языки - например джаваскрипт, руби). Который пройдется по урокам в курсе и разделит их на свои директории. 
Фишка в том, что уроки написаны в Yaml формате, а тексты в markdown, поэтому достаточно уметь прочитать ямл и взять нужные ключи, положить значения в отдельный файл.

**Comment by ola-9** [comment]
@fey можно [тут ](https://github.com/hexlet-components/hexlet-basics-exercises-utils)глянуть что получилось
