### ISSUE TITLE
Не отображается иконка чата поддержки в мобильной версии сайта

### ISSUE THREAD

**Issue by ElenaSimanina** [hexlet-basics/hexlet-basics#423]
На сайте реализован сервис - чат поддержки , в правом нижнем углу отображается иконка чата.  Если открыть сайт на мобильных устройствах,  иконка чата не отображается.  Если просматривать сайт  через консоль разработчика на разных мобильных устройствах, то иконка чата есть, но если обновить страницу, то иконка исчезает.  

_Воспроизводится:_
- Google Chrome  Версия 120.0.6099.130 (Официальная сборка), (64 бит)
ОС  Windows 10
- Мобильное устройство  ZTE Blade 20 Smart  модель ZTE 2050RU

![photo_2023-12-25_19-43-20](https://github.com/hexlet-basics/hexlet-basics/assets/135851722/a6d516f1-ac45-4478-8e36-1a2e4fcd641b)

https://github.com/hexlet-basics/hexlet-basics/assets/135851722/c7a7ccdc-5546-4e86-9b9e-722685020eb8

**Comment by fey** [comment]
Ответ от разработчиков - виджет скрыли на мобильной версии, чтобы не скрывать важные элементы управления.

**Comment by ElenaSimanina** [comment]
Все понятно!) Спасибо!))
