### ISSUE TITLE
Кнопка "продолжить" сохраняет свое состояние после прохождения курса

### ISSUE THREAD

**Issue by valeriySeregin** [hexlet-basics/hexlet-basics#58]
![image](https://user-images.githubusercontent.com/40579575/90366969-bec8a180-e070-11ea-9ce2-91d2fc6ec135.png)

На картинке красной рамкой выделены недопройденные курсы, там кнопка "продолжить" логична. Синей же рамкой выделены полностью пройденные курсы и наличие кнопки "продолжить" выглядит странно.

**Comment by mokevnin** [comment]
Используем слово "повторить"

**Comment by mokevnin** [comment]
Больше нет кнопки :D
