### ISSUE TITLE
Вопросы по навигации

### ISSUE THREAD

**Issue by amshkv** [hexlet-basics/hexlet-basics#83]
На сайте находится 3 навигационных меню разных, возможно можно объединить в один общий список
![image](https://user-images.githubusercontent.com/23584933/102457950-97043d00-4054-11eb-954c-c57c9f23b32d.png)

+ на мобильном блоки О проекте и Сообщество отличаются по отступам 
![image](https://user-images.githubusercontent.com/23584933/102458035-b69b6580-4054-11eb-948b-29161be76137.png)

**Comment by f1eeman** [comment]
забрал
