### ISSUE TITLE
При вводе неправильного пароля Password не переведён

### ISSUE THREAD

**Issue by burenkov-anton** [hexlet-basics/hexlet-basics#85]
![PasswordTranslation](https://user-images.githubusercontent.com/11513918/102716139-782fd000-430c-11eb-90ae-756cded1aa54.png)

**Comment by fey** [comment]
Актуально. 
![image](https://user-images.githubusercontent.com/697178/115960694-52217300-a52c-11eb-8c78-bfe97489ea19.png)

**Comment by mokevnin** [comment]
done
